baseurl = "https://sagamino.netlify.app/"
languageCode = "ja"
title = "相模湖畔 -Lakeside S-"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-2RM3ZTB734"
# Define the number of posts per page
paginate = 5
footnotereturnlinkcontents = "?"
theme = "icarus"
# Comment the themesDir option if you use this theme in production
themesDir = "themes"


[permalinks]
    post = "/:filename"


[params]
    # Tell me who you are
    author = "さがみの/Sagamino"
    bio = "Animation"
    location = "Sendai"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "/images/mashiro_02_0.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = ""
    logo = "/images/logo_01.png"
	images = ["/images/og_image.jpg"]
    og_image = ""
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["article","diary"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"


# [[params.menu]]
#     before = false
#     label  = "Tags"
#     link   = "tags/"

[[params.menu]]
    before = false
    label  = "Articles"
    link   = "article/"

[[params.menu]]
    before = false
    label  = "Diaries"
    link   = "diary/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/intent/follow?screen_name=sagami_no"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = ""
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "sagami_no"

    mastodon        = "@sagamino"
    annict          = "@sagamino"
    amazon          = "hz/wishlist/ls/28VXS1055QQRF?ref_=wl_share"


# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true